### ISSUE TITLE
Persist total number of URLs scanned

### ISSUE THREAD

**Issue by DecentralizedDan** [interlock-network/threatslayer#35]
Right now, bc we store the total number of URLs scanned by a user locally, the number gets reset every time the extension is refreshed.
* This number is important for the user to see and trust
* Therefore, it should persist
  * Implementation will probably be storing the total BE, which would require significant refactoring
  * Alternately, we may only track total URLs BE for users who register an account with us

GanttStart: 2023-09-01
GanttDue: 2023-11-30

**Comment by jmercouris** [comment]
The only way to do it will be to persist it for users who register with us. This can be the job of Galactus, the user will have an account, and it will store all of their information. The Octahedron can just focus on detection!

**Comment by jmercouris** [comment]
Of course there may very well be another way, that's the only way I can think of, right now.
